services:
  # Backend service
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: podback-api
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
